
policy: "MlpPolicy"
learning_rate: 3.0e-4
batch_size: 64
buffer_size: 100000
learning_starts: 1000
gamma: 0.99
target_update_interval: 10
train_freq: 256
gradient_steps: 128
exploration_fraction: 0.16
exploration_final_eps: 0.04
policy_kwargs:
  net_arch: [256, 256]
