policy: 'MlpPolicy'
learning_rate: 4.0e-3
batch_size: 128
buffer_size: 10000
learning_starts: 1000
gamma: 0.98
target_update_interval: 600
train_freq: 16
gradient_steps: 8
exploration_fraction: 0.2
exploration_final_eps: 0.07
policy_kwargs: 
  net_arch: [256, 256]